const SPORTSBOOK_FORMATS = {
  draftkings: {
    name: 'DraftKings',
    instructions: 'Go to DraftKings Sportsbook > Search for the game > Select the bet type > Enter stake'
  },
  fanduel: {
    name: 'FanDuel',
    instructions: 'Open FanDuel Sportsbook > Navigate to the game > Tap the odds > Enter wager amount'
  },
  betmgm: {
    name: 'BetMGM',
    instructions: 'Open BetMGM > Find the game in sports section > Select market > Add to bet slip > Enter amount'
  },
  caesars: {
    name: 'Caesars Sportsbook',
    instructions: 'Open Caesars app > Browse to the sport > Select the game > Pick your market > Enter stake'
  },
  pointsbetus: {
    name: 'PointsBet',
    instructions: 'Open PointsBet > Select sport > Find game > Choose bet type > Enter amount'
  },
  betrivers: {
    name: 'BetRivers',
    instructions: 'Open BetRivers > Navigate to sport > Select game > Add selection > Enter wager'
  },
  unibet_us: {
    name: 'Unibet',
    instructions: 'Open Unibet > Select sport from menu > Find game > Choose market > Place bet'
  },
  williamhill_us: {
    name: 'William Hill',
    instructions: 'Open William Hill app > Browse sports > Select game > Choose outcome > Enter stake'
  }
};

function americanToDecimal(odds) {
  if (odds > 0) return (odds / 100) + 1;
  return (100 / Math.abs(odds)) + 1;
}

function calculatePayout(stake, odds) {
  const decimal = americanToDecimal(odds);
  const payout = stake * decimal;
  const profit = payout - stake;
  return { payout: payout.toFixed(2), profit: profit.toFixed(2) };
}

function formatBetSlip(pick, bookmaker = null, stake = 10) {
  const sb = bookmaker ? SPORTSBOOK_FORMATS[bookmaker] : null;
  const odds = pick.bestOdds || -110;
  const { payout, profit } = calculatePayout(stake, odds);
  const oddsDisplay = odds > 0 ? `+${odds}` : `${odds}`;

  let slip = `=== INTELLABETS PICK ===\n`;
  slip += `${pick.homeTeam} vs ${pick.awayTeam}\n`;
  slip += `Sport: ${pick.sport || 'N/A'}\n`;
  slip += `BET: ${pick.recommendation}\n`;
  slip += `Odds: ${oddsDisplay}\n`;
  slip += `Confidence: ${pick.confidence}%\n`;
  slip += `Risk: ${pick.riskLevel || 'medium'}\n\n`;
  slip += `STAKE: $${stake}\n`;
  slip += `WIN: $${profit}\n`;
  slip += `TOTAL PAYOUT: $${payout}\n\n`;

  if (sb) {
    slip += `--- ${sb.name} ---\n`;
    slip += sb.instructions + '\n\n';
  }

  slip += `Reasoning: ${pick.reasoning || 'AI-generated pick'}\n`;
  slip += `Key Factors:\n`;
  (pick.keyFactors || []).forEach(f => { slip += `  - ${f}\n`; });
  slip += `\n[Generated by IntellaBets AI]\n`;

  return slip;
}

function formatParlaySlip(parlay, stake = 10) {
  const { payout, profit } = calculatePayout(stake, parlay.combinedOdds || 200);
  const oddsDisplay = (parlay.combinedOdds || 200) > 0
    ? `+${parlay.combinedOdds || 200}`
    : `${parlay.combinedOdds || 200}`;

  let slip = `=== INTELLABETS PARLAY ===\n`;
  slip += `${parlay.parlayLegs?.length || 0}-LEG PARLAY\n\n`;

  (parlay.parlayLegs || []).forEach((leg, i) => {
    const legOdds = leg.odds > 0 ? `+${leg.odds}` : `${leg.odds}`;
    slip += `LEG ${i + 1}: ${leg.recommendation} (${legOdds})\n`;
    if (leg.bookmaker) slip += `  Book: ${leg.bookmaker}\n`;
  });

  slip += `\nCombined Odds: ${oddsDisplay}\n`;
  slip += `Confidence: ${parlay.confidence}%\n`;
  slip += `Risk: ${parlay.riskLevel}\n\n`;
  slip += `STAKE: $${stake}\n`;
  slip += `WIN: $${profit}\n`;
  slip += `TOTAL PAYOUT: $${payout}\n\n`;
  slip += `Strategy: ${parlay.reasoning || 'AI-optimized parlay'}\n`;
  slip += `\n[Generated by IntellaBets AI]\n`;

  return slip;
}

module.exports = { formatBetSlip, formatParlaySlip, SPORTSBOOK_FORMATS };
